[ADD]: Summary for program compilation and units tests

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,8 +22,8 @@ jobs:
         run: |
           echo "## Summary report : :chart_with_upwards_trend:" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
-          echo "| ###Jobs | ###Status | ###Start | ###End |" >> $GITHUB_STEP_SUMMARY
-          echo "| ------- | --------- | -------- | ------ |" >> $GITHUB_STEP_SUMMARY
+          echo "| Jobs | Status | Start | End |" >> $GITHUB_STEP_SUMMARY
+          echo "| ---- | ------ | ----- | --- |" >> $GITHUB_STEP_SUMMARY
           echo -n "| Check unwanted files | " >> $GITHUB_STEP_SUMMARY
           error=0
           for file in $(git ls-files); do
@@ -44,13 +44,15 @@ jobs:
     container:
       image: epitechcontent/epitest-docker
     steps:
-      - name : Fetch repository
+      - name: Fetch repository
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
       - name: Print summary
         run: |
-          echo -n "| Program compilation " >> $GITHUB_STEP_SUMMARY
+          echo "| Jobs | Status | Start | End |" >> $GITHUB_STEP_SUMMARY
+          echo "| ---- | ------ | ----- | --- |" >> $GITHUB_STEP_SUMMARY
+          echo -n "| Program compilation | " >> $GITHUB_STEP_SUMMARY
       - name: Create build directory
         run: |
           mkdir ./build/
@@ -78,10 +80,15 @@ jobs:
     container:
       image: epitechcontent/epitest-docker
     steps:
-      - name : Fetch repository
+      - name: Fetch repository
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+      - name: Print summary
+        run: |
+          echo "| Jobs | Status | Start | End |" >> $GITHUB_STEP_SUMMARY
+          echo "| ---- | ------ | ----- | --- |" >> $GITHUB_STEP_SUMMARY
+          echo -n "| Unit tests | " >> $GITHUB_STEP_SUMMARY
       - name: Create build directory
         run: |
           mkdir ./build/
@@ -96,7 +103,7 @@ jobs:
           make tests_run
       - name: Run unit tests
         run: |
-          ./tests_run
+          ./tests_run && echo "Passed :white_check_mark: |" >> $GITHUB_STEP_SUMMARY || echo "Error :x: |" >> $GITHUB_STEP_SUMMARY
 
   run_functionals_tests:
     runs-on: ubuntu-latest
