[FIX]: retore main repository to tests on real arcade

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,71 +1,188 @@
 name: chocolatine
 env:
   MIRROR_URL: git@github.com:EpitechPromo2026/B-OOP-400-NAN-4-1-arcade-andreas.le-tanter.git
-  EXECUTABLES: "arcade"
+  EXECUTABLE: "arcade"
+  UNWANTED_FILES: '^(.*\/)*((.*\.(([ao])|(so)|(gcno)|(gcda)|(gcov)))|(^.*\~)|(.*\/tmp\/.+)|(#.*\#))$'
 on:
   push:
   pull_request:
     types: [created]
     branches-ignore:
       - 'ga-ignore-*'
+
 jobs:
-  push_to_mirror: 
-    if: github.event_name == 'push'
-    runs-on: ubuntu-latest
-    needs: [run_tests]
-    steps:
-      - uses: actions/checkout@v3
-        with:
-            fetch-depth: 0
-      - uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url:
-            ${{ env.MIRROR_URL }}
-          ssh_private_key:
-            ${{ secrets.SSH_KEY }}
   check_repository_cleanliness:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - run: |
-          myArray=('*/#*#' '*/*~' '*/*pain_au_chocolat*' '*/*.o' '*/*.a' '*/*.so' '*/*.gcno' '*/*.gcda' '*/*.gcov' '#*#' '*~' '*pain_au_chocolat*' '*.o' '*.a' '*.so' '*.gcno' '*.gcda' '*.gcov' 'tmp/*' '*/tmp/*')
-          find=0
-          for str in ${myArray[@]}; do
-              file_count=$(find "." -print | grep "$str" | wc -l)
-              if [[ $file_count -gt 0 ]]; then
-                  echo "::error title="Unwanted file detected: $str#L1"::$str"
-                  find=1
-              fi
+      - name: Fetch repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Check unwanted files
+        run: |
+          echo "## Summary report : :chart_with_upwards_trend:" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "| ###Jobs | ###Status | ###Start | ###End |" >> $GITHUB_STEP_SUMMARY
+          echo "| ------- | --------- | -------- | ------ |" >> $GITHUB_STEP_SUMMARY
+          echo -n "| Check unwanted files | " >> $GITHUB_STEP_SUMMARY
+          error=0
+          for file in $(git ls-files); do
+            if [[ $file =~ $UNWANTED_FILES ]]; then
+              echo "::error title=Unwanted file detected::File $file is not allowed in the repository."
+              error=1
+            fi
           done
-          if [ "$find" -eq "1" ]; then
+          if [ $error -eq 1 ]; then
+            echo "Error :x: |" >> $GITHUB_STEP_SUMMARY
             exit 1
           fi
+          echo "Passed :white_check_mark: |" >> $GITHUB_STEP_SUMMARY
+
   check_program_compilation:
     runs-on: ubuntu-latest
     needs: [check_repository_cleanliness]
     container:
       image: epitechcontent/epitest-docker
     steps:
-      - uses: actions/checkout@v3
-      - run: cmake CMakeLists.txt
-      - run: make
-        timeout-minutes: 2
-      - run: |
-          IFS=','
-          read -a strarr <<< "${{ env.EXECUTABLES }}"
-          for name in ${strarr[@]}; do
-              file_count=$(find "." -type f -perm -a=x -print | grep "$name" | wc -l)
-              if [[ $file_count -eq "0" ]]; then
-                  exit 1
-              fi
-          done
-  run_tests:
+      - name : Fetch repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Print summary
+        run: |
+          echo -n "| Program compilation " >> $GITHUB_STEP_SUMMARY
+      - name: Create build directory
+        run: |
+          mkdir ./build/
+      - name: Go to build directory
+        run: |
+          cd ./build/
+      - name: Build project
+        run: |
+          cmake .
+      - name: Compile project
+        run: |
+          make
+      - name: Check if executable exists
+        run: |
+          if [ ! -f $EXECUTABLE ]; then
+            echo "::error title=Executable not found::The executable $EXECUTABLE was not found."
+            echo "Error :x: |" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          echo "Passed :white_check_mark: |" >> $GITHUB_STEP_SUMMARY
+
+  run_units_tests:
     runs-on: ubuntu-latest
-    needs: [check_program_compilation]
+    needs: [check_repository_cleanliness]
     container:
       image: epitechcontent/epitest-docker
     steps:
-      - uses: actions/checkout@v3
-      - run: cmake CMakeLists.txt
-      - run: make tests_run
-        timeout-minutes: 2
+      - name : Fetch repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Create build directory
+        run: |
+          mkdir ./build/
+      - name: Go to build directory
+        run: |
+          cd ./build/
+      - name: Build project
+        run: |
+          cmake CMakeLists.txt
+      - name: Compile unit tests
+        run: |
+          make tests_run
+      - name: Run unit tests
+        run: |
+          ./tests_run
+
+  run_functionals_tests:
+    runs-on: ubuntu-latest
+    needs: [check_repository_cleanliness]
+    container:
+      image: epitechcontent/epitest-docker
+    steps:
+      - name : Fetch repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Install Rust
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          repository: Atomot/ftest
+      - name: Go to ftest directory
+        run: |
+          ls -la
+      - name: install ftest
+        run: |
+          cargo build --release -p ftest
+      - name: Create build directory
+        run: |
+          mkdir ./build/
+      - name: Go to build directory
+        run: |
+          cd ./build/
+      - name: Build project
+        run: |
+          cmake CMakeLists.txt
+      - name: Compile functionals tests
+        run: |
+          make functinals_tests_run
+      - name: Run functinals tests
+        run: |
+          ./functinals_tests_run
+
+  create_release:
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+    needs: [check_program_compilation, run_units_tests, run_functionals_tests]
+    steps:
+      - name: Fetch repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Create release
+        run: |
+          echo "Creating release..."
+
+  create_doxygen:
+    runs-on: ubuntu-latest
+    needs: [check_program_compilation, run_units_tests, run_functionals_tests]
+    steps:
+      - name : Fetch repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Install Doxygen
+        run: |
+          echo "Installing Doxygen..."
+      - name: Generate Doxygen documentation
+        run: |
+          echo "Generating Doxygen documentation..."
+      - name: Deploy documentation
+        run: |
+          echo "Deploying documentation..."
+
+  push_to_mirror:
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+    needs: [create_release, create_doxygen]
+    steps:
+      - name: Fetch repository
+        uses: actions/checkout@v3
+        with:
+            fetch-depth: 0
+      - name: Push to mirror
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.SSH_KEY }}
